development:
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: dpla_portal_development

test:
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: dpla_portal_test

production:
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: dpla_portal_production
