##
# This file associates rightstatement.org URIs with their lables, definitions,
# and image paths.
# @see rightsstatements.org and /app/assets/images/rights_statements

"http://rightsstatements.org/vocab/InC/1.0/":
  label: "In copyright"
  image_path: "rights_statements/InC.dark-white-interior-blue-type.png"
  definition: "This Item is protected by copyright and/or related rights. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use. For other uses you need to obtain permission from the rights-holder(s)."

"http://rightsstatements.org/vocab/InC-OW-EU/1.0/":
  label: "In copyright - EU orphan work"
  image_path: "rights_statements/InC-OW-EU.dark-white-interior-blue-type.png"
  definition: "This Item has been identified as an orphan work in the country of first publication and in line with Directive 2012/28/EU of the European Parliament and of the Council of 25 October 2012 on certain permitted uses of orphan works. For this Item, either (a) no rights-holder(s) have been identified or (b) one or more rights-holder(s) have been identified but none have been located even though a diligent search for the rights-holder(s) has been conducted. The results of the diligent search are available in the EU Orphan Works Database. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use."

"http://rightsstatements.org/vocab/InC-EDU/1.0/":
  label: "In copyright - educational use permitted"
  image_path: "rights_statements/InC-EDU.dark-white-interior-blue-type.png"
  definition: "This Item is protected by copyright and/or related rights. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use. In addition, no permission is required from the rights-holder(s) for educational uses. For other uses, you need to obtain permission from the rights-holder(s)."

"http://rightsstatements.org/vocab/InC-NC/1.0/":
  label: "In copyright - non-commercial use permitted"
  image_path: "rights_statements/InC-NC.dark-white-interior-blue-type.png"
  definition: "This Item is protected by copyright and/or related rights. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use. In addition, no permission is required from the rights-holder(s) for non-commercial uses. For other uses you need to obtain permission from the rights-holder(s)."
  
"http://rightsstatements.org/vocab/InC-RUU/1.0/":
  label: "In copyright - rights-holder(s) unlocatable or unidentifiable"
  image_path: "rights_statements/InC-RUU.dark-white-interior-blue-type.png"
  definition: "This Item is protected by copyright and/or related rights. However, for this Item, either (a) no rights-holder(s) have been identified or (b) one or more rights-holder(s) have been identified but none have been located. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use."

"http://rightsstatements.org/vocab/NoC-CR/1.0/":
  label: "No copyright - contractual restrictions"
  image_path: "rights_statements/NoC-CR.dark-white-interior-blue-type.png"
  definition: "Use of this Item is not restricted by copyright and/or related rights. As part of the acquisition or digitization of this Item, the organization that has made the Item available is contractually required to limit the use of this Item. Limitations may include, but are not limited to, privacy issues, cultural protections, digitization agreements or donor agreements. Please refer to the organization that has made the Item available for more information."

"http://rightsstatements.org/vocab/NoC-NC/1.0/":
  label: "No copyright - non-commerical use only"
  image_path: "rights_statements/NoC-NC.dark-white-interior-blue-type.png"
  definition: "This object has been digitized in a public-private partnership. As part of this partnership, the partners have agreed to limit commercial uses of this digital representation of the object by third parties. You can, without permission, copy, modify, distribute, display, or perform the digital object, for non-commercial uses. For any other permissible uses, please review the terms and conditions of the organization that has made the item available."

"http://rightsstatements.org/vocab/NoC-OKLR/1.0/":
  label: "No copyright - other known legal restrictions"
  image_path: "rights_statements/NoC-OKLR.dark-white-interior-blue-type.png"
  definition: "Use of this Item is not restricted by copyright and/or related rights. In one or more jurisdictions, laws other than copyright are known to impose restrictions on the use of this Item. Please refer to the organization that has made the Item available for more information."

"http://rightsstatements.org/vocab/NoC-US/1.0/":
  label: "No copyright - United States"
  image_path: "rights_statements/NoC-US.dark-white-interior-blue-type.png"
  definition: "The organization that has made the Item available believes that the Item is in the Public Domain under the laws of the United States, but a determination was not made as to its copyright status under the copyright laws of other countries. The Item may not be in the Public Domain under the laws of other countries. Please refer to the organization that has made the Item available for more information."

"http://rightsstatements.org/vocab/CNE/1.0/":
  label: "Copyright not evaluated"
  image_path: "rights_statements/CNE.dark-white-interior-blue-type.png"
  definition: "The copyright and related rights status of this Item has not been evaluated. Please refer to the organization that has made the Item available for more information. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use."

"http://rightsstatements.org/vocab/UND/1.0/":
    label: "Copyright undetermined"
    image_path: "rights_statements/UND.dark-white-interior-blue-type.png"
    definition: "The copyright and related rights status of this Item has been reviewed by the organization that has made the Item available, but the organization was unable to make a conclusive determination as to the copyright status of the Item. Please refer to the organization that has made the Item available for more information. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use."

"http://rightsstatements.org/vocab/NKC/1.0/":
    label: "No known copyright"
    image_path: "rights_statements/NKC.dark-white-interior-blue-type.png"
    definition: "The organization that has made the Item available reasonably believes that the Item is not restricted by copyright or related rights, but a conclusive determination could not be made. Please refer to the organization that has made the Item available for more information. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use."

"https://creativecommons.org/publicdomain/zero/1.0/":

"https://creativecommons.org/licenses/by/4.0/":

"https://creativecommons.org/licenses/by-sa/4.0/":

"https://creativecommons.org/licenses/by-nc/4.0/":

"https://creativecommons.org/licenses/by-nd/4.0/":

"https://creativecommons.org/licenses/by-nc-sa/4.0/":

"https://creativecommons.org/licenses/by-nc-nd/4.0/":

"https://creativecommons.org/publicdomain/mark/1.0/":
