url:
  host: portal.dp.la
  port: 80
notifications:
  from: welcome@portal.dp.la
api:
  url: http://integration1.qa.dp.la/v2
  username: dpla
  password: dpla
exhibitions:
  site: http://localhost:8080
  elasticsearch:
    host: http://localhost:9200
    default_index: omeka
googleanalytics:
  tracker: UA-38671601-1