#Use this file to define settings related to application configuration
#Use this file to define settings that are UNIVERSAL (not specific to any environment)
#Information in this file will be PUBLIC (this file is tracked in git)
#Declarations in config/settings.local.yml override declarations in this file

# User interface tweaks
ui:
  # Items
  items:
    # Default thumbnails for items without thumbnail
    # Mapping default thumbnails to sourceResource.type field
    # Text thumbnail will be displayed for unmatched types
    default_thumbnails:
      image:
        - image
      sound:
        - sound
      video:
  maps:
    center: [38, -93]
    zoom:
      start: 3
      min:  2
      max: 18
    grid_size:
      cols: 5
      rows: 3
    state_level: [4, 6]
    grid_level: [7, 18]
    page_size: 500
    popup_page_size: 50
