# Used for generation links in emails
url:
  host: portal.dp.la
  port: 80
# Email notifications to users sended from
notifications:
  from: welcome@portal.dp.la
# DPLA API URL and credentials
api:
  url: http://198.101.129.127/v2
  # Username and password for Basic HTTP Auth to API
  username:
  password:
  # API key, will be added to all API requests as &api_key=
  api_key:
exhibitions:
  # Omeka exhibition site address. Used for generating link
  site: http://localhost:8080
  # Elasticsearch instance for searching exhibitions
  elasticsearch:
    host: http://localhost:9200
    default_index: omeka
# Google Analytics account
googleanalytics:
  tracker: UA-38671601-1
# Sessions settings
session:
  # Store settings. cookie_store and dalli_store are available
  store: dalli_store
  key: _dpla_frontend
  # Settings for memcache sessions
  dalli_store:
    memcache_server:
      - localhost