# Used for generation links in emails
url:
  host: portal.dp.la
  port: 80
# Email notifications to users sended from
notifications:
  from: welcome@portal.dp.la
# DPLA API URL and credentials
api:
  url: http://integration1.qa.dp.la/v2
  username: username
  password: password
exhibitions:
  # Omeka exhibition site address. Used for generating link
  site: http://localhost:8080
  # Elasticsearch instance for searching exhibitions
  elasticsearch:
    host: http://localhost:9200
    default_index: omeka
# Google Analytics account
googleanalytics:
  tracker: UA-38671601-1