url:
  host: portal.dp.la
  port: 80
notifications:
  from: welcome@portal.dp.la
api:
  url: http://api.dp.la/dev
exhibitions:
  site: http://localhost
  elasticsearch: http://localhost:9200
googleanalytics:
  tracker: UA-38671601-1