# Used for generation links in emails
url:
  host: portal.dp.la
  port: 80
# Email notifications to users sended from
notifications:
  from: welcome@portal.dp.la
# DPLA API URL and credentials
api:
  url: http://198.101.129.127/v2
  # Username and password for Basic HTTP Auth to API
  username:
  password:
  # API key, will be added to all API requests as &api_key=
  key:
exhibitions:
  # Omeka exhibition site address. Used for generating link
  site: http://localhost:8080
  # Elasticsearch instance for searching exhibitions
  elasticsearch:
    host: http://localhost:9200
    default_index: omeka
wordpress:
  # Wordpress site for building links to pages served by WP
  site: http://localhost:4000
apps:
  become_app_developer: http://dp.la/info/developers
# Google Analytics account
googleanalytics:
  tracker: UA-28197764-1
# Sessions settings
session:
  # Name of cookie indicator is user signed in or not
  # Userful for serving cached pages for guest users
  logged_in_flag: _dpla_no_cache
  # Store settings. cookie_store and dalli_store are available
  store: dalli_store
  key: _dpla_frontend
  # Settings for memcache sessions
  dalli_store:
    memcache_server:
      - localhost
widgets:
  twitter_username: dpla
  # URL of wordpress site.
  # NOTE: JSON API plugin is required to able read Wordpress feed as JSONP requests
  wordpress_url: http://dp.la
  # Urls for social icons
  social_icons:
    facebook: https://www.facebook.com/theDPLA
    twitter: https://twitter.com/dpla
    rss: http://dp.la/feed
# User interface tweaks
ui:
  # Items
  items:
    # Default thumbnails for items without thumbnail
    # Mapping default thumbnails to sourceResource.type field
    # Text thumbnail will be displayed for unmatched types
    default_thumbnails:
      image:
        - image
      sound:
        - sound
      video: